# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ayIz1PkPXtr5bIq_RtcDUNciCthv_6M
"""

!pip install pandas numpy scikit-learn -q

import pandas as pd
import numpy as np
import sqlite3
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler

print("="*60)
print("BANK KREDIT SKORING TIZIMI")
print("="*60)

ulanish = sqlite3.connect('bank_baza.db')
kursor = ulanish.cursor()

kursor.execute("DROP TABLE IF EXISTS mijozlar")
kursor.execute("DROP TABLE IF EXISTS kredit_tarixi")

kursor.execute('''
    CREATE TABLE mijozlar (
        passport TEXT PRIMARY KEY,
        ism TEXT,
        yosh INTEGER,
        rasmiy_daromad REAL,
        norasmiy_daromad REAL,
        turmush_daromadi REAL,
        ish_staji REAL,
        farzand_soni INTEGER,
        ijara REAL
    )
''')

kursor.execute('''
    CREATE TABLE kredit_tarixi (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        passport TEXT,
        kechikish INTEGER,
        holat TEXT
    )
''')

np.random.seed(42)

for i in range(500):
    passport = f"AA{np.random.randint(10000000, 99999999)}"
    yosh = np.random.randint(22, 65)
    ism = f"Mijoz_{i}"
    rasmiy = np.random.uniform(2000000, 20000000)
    norasmiy = np.random.uniform(0, 5000000)
    turmush = np.random.uniform(0, 8000000)
    staj = np.random.uniform(0.5, 35)
    farzand = np.random.poisson(1.5)
    ijara = np.random.uniform(0, 2000000)

    kursor.execute('INSERT INTO mijozlar VALUES (?,?,?,?,?,?,?,?,?)',
                   (passport, ism, yosh, rasmiy, norasmiy, turmush, staj, farzand, ijara))

    kechikish = np.random.poisson(0.3)
    holat = 'TOLANGAN' if kechikish == 0 else 'MUAMMOLI'
    kursor.execute('INSERT INTO kredit_tarixi (passport, kechikish, holat) VALUES (?,?,?)',
                   (passport, kechikish, holat))

ulanish.commit()
print("Baza yaratildi")

kursor.execute("SELECT * FROM mijozlar")
malumotlar = kursor.fetchall()

mijozlar = []
for m in malumotlar:
    passport, ism, yosh, rasmiy, norasmiy, turmush, staj, farzand, ijara = m

    kursor.execute("SELECT SUM(kechikish) FROM kredit_tarixi WHERE passport=?", (passport,))
    kechikish = kursor.fetchone()[0] or 0

    kursor.execute("SELECT holat FROM kredit_tarixi WHERE passport=? ORDER BY id DESC LIMIT 1", (passport,))
    oxirgi = kursor.fetchone()

    umumiy_daromad = rasmiy + norasmiy + turmush
    umumiy_xarajat = (rasmiy * 0.3) + ijara + (farzand * 300000)
    dti = (rasmiy * 0.3) / (rasmiy + 1) * 100

    if oxirgi and oxirgi[0] == 'TOLANGAN':
        toladi = 1
    elif oxirgi and oxirgi[0] == 'MUAMMOLI':
        toladi = 0
    else:
        toladi = np.random.choice([0,1], p=[0.3, 0.7])

    mijozlar.append({
        'passport': passport,
        'yosh': yosh,
        'rasmiy_daromad': rasmiy,
        'norasmiy_daromad': norasmiy,
        'turmush_daromadi': turmush,
        'ish_staji': staj,
        'farzand_soni': farzand,
        'ijara': ijara,
        'umumiy_daromad': umumiy_daromad,
        'umumiy_xarajat': umumiy_xarajat,
        'dti': dti,
        'kechikish': kechikish,
        'toladi': toladi
    })

df = pd.DataFrame(mijozlar)
print(f"Bazada {len(df)} ta mijoz bor")

xususiyatlar = ['yosh', 'rasmiy_daromad', 'norasmiy_daromad', 'turmush_daromadi',
                'ish_staji', 'farzand_soni', 'ijara', 'dti', 'kechikish']

X = df[xususiyatlar]
y = df['toladi']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

masshtab = StandardScaler()
X_train = masshtab.fit_transform(X_train)
X_test = masshtab.transform(X_test)

model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

ehtimol = model.predict_proba(X_test)[:, 1]
auc = roc_auc_score(y_test, ehtimol)
print(f"Model aniqligi (AUC): {auc:.4f}")

print("\n" + "="*60)
print("MIJOZNI TEKSHIRISH")
print("="*60)

passport = input("\nPassport raqamini kiriting: ")

kursor.execute("SELECT * FROM mijozlar WHERE passport=?", (passport,))
mijoz = kursor.fetchone()

if mijoz:
    passport, ism, yosh, rasmiy, norasmiy, turmush, staj, farzand, ijara = mijoz

    kursor.execute("SELECT SUM(kechikish) FROM kredit_tarixi WHERE passport=?", (passport,))
    kechikish = kursor.fetchone()[0] or 0

    umumiy_daromad = rasmiy + norasmiy + turmush
    umumiy_xarajat = (rasmiy * 0.3) + ijara + (farzand * 300000)
    dti = (rasmiy * 0.3) / (rasmiy + 1) * 100

    skoring = 0
    if 25 <= yosh <= 50:
        skoring += 30
    if rasmiy >= 10000000:
        skoring += 30
    elif rasmiy >= 5000000:
        skoring += 20
    else:
        skoring += 10
    if staj >= 5:
        skoring += 25
    elif staj >= 2:
        skoring += 15
    else:
        skoring += 5
    if kechikish == 0:
        skoring += 25
    elif kechikish <= 2:
        skoring += 10
    else:
        skoring -= 20

    mijoz_x = pd.DataFrame([[
        yosh, rasmiy, norasmiy, turmush, staj, farzand, ijara, dti, kechikish
    ]], columns=xususiyatlar)

    mijoz_x = masshtab.transform(mijoz_x)
    ml_ehtimol = model.predict_proba(mijoz_x)[0, 1]

    biznes = True
    sabab = []
    if yosh < 18:
        biznes = False
        sabab.append("Yosh 18 dan kichik")
    if yosh > 70:
        biznes = False
        sabab.append("Yosh 70 dan katta")
    if staj < 1:
        biznes = False
        sabab.append("Ish staji 1 yildan kam")
    if kechikish >= 3:
        biznes = False
        sabab.append("Kechikishlar 3 dan kop")
    if rasmiy < 2000000:
        biznes = False
        sabab.append("Rasmiy daromad 2 milliondan kam")

    print(f"\nMijoz: {ism}")
    print(f"Yosh: {yosh}")
    print(f"Rasmiy daromad: {rasmiy:,.0f} so'm")
    print(f"Norasmiy daromad: {norasmiy:,.0f} so'm")
    print(f"Turmush ortogi: {turmush:,.0f} so'm")
    print(f"Jami daromad: {umumiy_daromad:,.0f} so'm")
    print(f"Farzandlar: {farzand} ta")
    print(f"Ish staji: {staj} yil")
    print(f"Kechikishlar: {kechikish} marta")
    print(f"Skoring ball: {skoring}")
    print(f"ML ehtimoli: {ml_ehtimol:.2%}")

    print("\n" + "="*60)
    if biznes and ml_ehtimol >= 0.5:
        print("NATIJA: KREDIT BERISH MUMKIN")

        if ml_ehtimol >= 0.85:
            foiz = 22
        elif ml_ehtimol >= 0.75:
            foiz = 24
        elif ml_ehtimol >= 0.65:
            foiz = 26
        else:
            foiz = 28

        print(f"Taklif etilayotgan foiz: {foiz}%")
    else:
        print("NATIJA: KREDIT BERILMAYDI")
        if not biznes:
            for s in sabab:
                print(f"Sabab: {s}")
        if ml_ehtimol < 0.5:
            print(f"Sabab: ML modelga kora xavf yuqori ({ml_ehtimol:.2%})")
else:
    print("\nYangi mijoz! Malumotlaringizni kiriting:")

    ism = input("Ismingiz: ")
    yosh = int(input("Yoshingiz: "))
    rasmiy = int(input("Rasmiy oylik daromadingiz: "))
    norasmiy = int(input("Norasmiy oylik daromadingiz: "))
    turmush = int(input("Turmush ortogi daromadi: "))
    staj = float(input("Umumiy ish stajingiz (yil): "))
    farzand = int(input("Farzandlar soni: "))
    ijara = int(input("Oylik ijara (ozingizniki 0): "))

    kursor.execute('INSERT INTO mijozlar VALUES (?,?,?,?,?,?,?,?,?)',
                   (passport, ism, yosh, rasmiy, norasmiy, turmush, staj, farzand, ijara))
    kursor.execute('INSERT INTO kredit_tarixi (passport, kechikish, holat) VALUES (?,?,?)',
                   (passport, 0, 'YANGI'))
    ulanish.commit()

    print("\nSiz bank mijozlari qatoriga qoshildingiz!")
    print("Endi kredit so'rashingiz mumkin.")

ulanish.close()
print("\n" + "="*60)