# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSW82Pi8ucwnVc__yjy6l49yj7GLRvF3
"""

import pandas as pd
import numpy as np
import os
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

BAZA_FILE = 'bank_baza_50.csv'
MODEL_FILE = 'kredit_modeli_50.pkl'

def hisobla_kredit_riski(row):
    risk_ball = 0

    if row['kredit_tarixi'] == 'yomon':
        risk_ball -= 50
    elif row['kredit_tarixi'] == 'yaxshi':
        risk_ball += 35
    else:
        risk_ball += 10

    daromad_qarz = row['jami_qarz'] / max(row['daromad'], 1)
    if daromad_qarz > 4:
        risk_ball -= 45
    elif daromad_qarz < 1.5:
        risk_ball += 20

    if row['kechiktirilgan_tolovlar'] > 5:
        risk_ball -= 50
    elif row['kechiktirilgan_tolovlar'] == 0:
        risk_ball += 25

    if row['ish_staji'] > 8:
        risk_ball += 20
    elif row['ish_staji'] < 2:
        risk_ball -= 30

    if row['kafil_bormi'] == 'ha':
        risk_ball += 25
        if row['kafil_daromadi'] > 5000:
            risk_ball += 15
        if row['kafil_kredit_tarixi'] == 'yaxshi':
            risk_ball += 10
    else:
        risk_ball -= 20

    if row['ish_joyi_turi'] == 'davlat':
        risk_ball += 25
    elif row['ish_joyi_turi'] == 'xususiy':
        risk_ball += 10
    elif row['ish_joyi_turi'] == 'ozini_ishi':
        risk_ball -= 10
    else:
        risk_ball -= 40

    if row['yosh'] > 55:
        risk_ball -= 15
    elif row['yosh'] < 23:
        risk_ball -= 10

    if row['oylik_majburiyat'] > row['daromad'] * 0.5:
        risk_ball -= 25

    return 1 if risk_ball > 0 else 0

def yarat_baza_50():
    np.random.seed(42)

    ismlar = ['Ali Valiyev', 'Zarina Aliyeva', 'Bekzod Rahimov', 'Dilnoza Karimova', 'Jasur Toshmatov',
              'Gulnora Saidova', 'Shoxrux Azimov', 'Nigora Abdullayeva', 'Sardorbek Xamraliev', 'Madina Rasulova',
              'Farrux Normatov', 'Sevara Xakimova', 'Jamshid Aliyev', 'Lobar Turayeva', 'Ulugbek Qodirov',
              'Nodira Eshmatova', 'Oxunjon Sobirov', 'Mohira Qobilova', 'Doniyor Turgunov', 'Nilufar Xolmatova',
              'Islom Karimov', 'Dildora Omonova', 'Sherzod Narziyev', 'Maftuna Juraeva', 'Rustam Gofurov',
              'Feruza Safarova', 'Jahongir Xaydarov', 'Charos Abdusalomova', 'Murod Ortiqov', 'Barno Qodirova',
              'Izzatilloxon Sultonov', 'Shahzoda Abdullayeva', 'Boburmirzo Shodiyev', 'Zuhra Ismoilova', 'Sherali Ahmedov',
              'Madinabonu Rahmatova', 'Husan Boymurodov', 'Mushtariy Xolmirzayeva', 'Asliddin Shukurov', 'Gulchehra Valiyeva',
              'Ravshan Shermatov', 'Sevinch Saidova', 'Mirkomil Usmonov', 'Ozoda Ergasheva', 'Umidjon Rahmonov',
              'Mahliyo Isroilova', 'Doston Hamroyev', 'Maftuna Zokirova', 'Shohruh Rajabov', 'Shirin Xamidullayeva']

    pasport_seriyalar = ['AA', 'AB', 'AC', 'AD', 'AE', 'BA', 'BB', 'BC', 'BD', 'BE'] * 5
    pasport_raqamlar = np.random.randint(100000, 999999, 50)

    baza = pd.DataFrame()
    baza['pasport'] = [f"{pasport_seriyalar[i]}-{pasport_raqamlar[i]}" for i in range(50)]
    baza['ism_familya'] = ismlar[:50]
    baza['yosh'] = np.random.randint(22, 65, 50)
    baza['daromad'] = np.random.randint(1500, 25000, 50)
    baza['kredit_tarixi'] = np.random.choice(['yaxshi', 'normal', 'yomon'], 50, p=[0.45, 0.35, 0.20])
    baza['jami_qarz'] = np.random.randint(0, 80000, 50)
    baza['ish_staji'] = np.random.randint(0, 35, 50)
    baza['mavjud_kreditlar'] = np.random.randint(0, 4, 50)
    baza['kechiktirilgan_tolovlar'] = np.random.randint(0, 8, 50)
    baza['kafil_bormi'] = np.random.choice(['ha', 'yoq'], 50, p=[0.6, 0.4])
    baza['kafil_daromadi'] = np.where(baza['kafil_bormi'] == 'ha', np.random.randint(3000, 20000, 50), 0)
    baza['kafil_kredit_tarixi'] = np.where(baza['kafil_bormi'] == 'ha',
                                           np.random.choice(['yaxshi', 'normal', 'yomon'], 50, p=[0.5, 0.3, 0.2]), 'none')
    baza['ish_joyi_turi'] = np.random.choice(['davlat', 'xususiy', 'ozini_ishi', 'ishsiz'], 50, p=[0.4, 0.35, 0.15, 0.1])
    baza['oylik_majburiyat'] = np.random.randint(0, 5000, 50)

    baza['kredit_berilsinmi'] = baza.apply(hisobla_kredit_riski, axis=1)

    return baza

def oqit_model(baza):
    oz_features = ['yosh', 'daromad', 'jami_qarz', 'ish_staji', 'mavjud_kreditlar',
                   'kechiktirilgan_tolovlar', 'oylik_majburiyat', 'kafil_daromadi']

    label_encoders = {}
    kategoriklar = ['kredit_tarixi', 'kafil_bormi', 'ish_joyi_turi']

    for col in kategoriklar:
        le = LabelEncoder()
        baza[col + '_encoded'] = le.fit_transform(baza[col])
        label_encoders[col] = le
        oz_features.append(col + '_encoded')

    X = baza[oz_features]
    y = baza['kredit_berilsinmi']

    model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
    model.fit(X, y)

    joblib.dump(model, MODEL_FILE)
    joblib.dump(label_encoders, 'label_encoders_50.pkl')
    joblib.dump(oz_features, 'oz_features_50.pkl')

    return model, label_encoders, oz_features

def yangi_mijoz_qoshish(baza, model, label_encoders, oz_features):
    print("\n" + "="*60)
    print("YANGI MIJOZ QOSHISH")
    print("="*60)

    pasport = input("Pasport (masalan: AA-123456): ").upper()

    if pasport in baza['pasport'].values:
        print(f"{pasport} allaqachon bazada mavjud!")
        return baza, model, label_encoders, oz_features

    print("\nYangi mijoz malumotlarini kiriting:")
    ism = input("Ism/familiya: ")
    yosh = int(input("Yosh: "))
    daromad = int(input("Oylik daromad (som): "))
    kredit_tarixi = input("Kredit tarixi (yaxshi/normal/yomon): ")
    jami_qarz = int(input("Jami qarz miqdori (som): "))
    ish_staji = int(input("Ish staji (yil): "))
    mavjud_kreditlar = int(input("Mavjud kreditlar soni: "))
    kechiktirilgan_tolovlar = int(input("Kechiktirilgan tolovlar soni: "))
    kafil_bormi = input("Kafil bormi (ha/yoq): ")
    ish_joyi_turi = input("Ish joyi turi (davlat/xususiy/ozini_ishi/ishsiz): ")

    if kafil_bormi == 'ha':
        kafil_daromadi = int(input("Kafil daromadi (som): "))
        kafil_kredit_tarixi = input("Kafil kredit tarixi (yaxshi/normal/yomon): ")
    else:
        kafil_daromadi = 0
        kafil_kredit_tarixi = 'none'

    oylik_majburiyat = int(input("Oylik majburiyat (som): "))

    yangi = pd.DataFrame([{
        'pasport': pasport,
        'ism_familya': ism,
        'yosh': yosh,
        'daromad': daromad,
        'kredit_tarixi': kredit_tarixi,
        'jami_qarz': jami_qarz,
        'ish_staji': ish_staji,
        'mavjud_kreditlar': mavjud_kreditlar,
        'kechiktirilgan_tolovlar': kechiktirilgan_tolovlar,
        'kafil_bormi': kafil_bormi,
        'kafil_daromadi': kafil_daromadi,
        'kafil_kredit_tarixi': kafil_kredit_tarixi,
        'ish_joyi_turi': ish_joyi_turi,
        'oylik_majburiyat': oylik_majburiyat
    }])

    yangi['kredit_berilsinmi'] = hisobla_kredit_riski(yangi.iloc[0])

    baza = pd.concat([baza, yangi], ignore_index=True)
    baza.to_csv(BAZA_FILE, index=False)

    print("\nModel yangilanmoqda...")
    model, label_encoders, oz_features = oqit_model(baza)

    print(f"\nYangi mijoz qoshildi va saqlandi!")
    if yangi['kredit_berilsinmi'].values[0] == 1:
        print("Kredit qarori: BERILADI")
    else:
        print("Kredit qarori: BERILMAYDI")

    return baza, model, label_encoders, oz_features

def mijozni_tekshirish(baza, model, label_encoders, oz_features):
    print("\n" + "="*60)
    print("MIJOZNI TEKSHIRISH")
    print("="*60)

    pasport = input("Pasportni kiriting (masalan: AA-123456): ").upper()

    if pasport not in baza['pasport'].values:
        print(f"\n{pasport} pasportli mijoz bazada topilmadi!")
        qosh = input("Yangi mijoz qoshish kerakmi? (ha/yoq): ")
        if qosh == 'ha':
            baza, model, label_encoders, oz_features = yangi_mijoz_qoshish(baza, model, label_encoders, oz_features)
        return baza, model, label_encoders, oz_features

    mijoz = baza[baza['pasport'] == pasport].iloc[0]

    print("\n" + "="*60)
    print("MIJOZ MALUMOTLARI")
    print("="*60)
    print(f"Pasport: {mijoz['pasport']}")
    print(f"Ism/familiya: {mijoz['ism_familya']}")
    print(f"Yosh: {mijoz['yosh']} yosh")
    print(f"Daromad: {mijoz['daromad']:,} som")
    print(f"Kredit tarixi: {mijoz['kredit_tarixi'].upper()}")
    print(f"Jami qarz: {mijoz['jami_qarz']:,} som")
    print(f"Ish staji: {mijoz['ish_staji']} yil")
    print(f"Mavjud kreditlar: {mijoz['mavjud_kreditlar']} ta")
    print(f"Kechiktirilgan tolovlar: {mijoz['kechiktirilgan_tolovlar']} marta")
    print(f"Kafil: {'HA' if mijoz['kafil_bormi'] == 'ha' else 'YOQ'}")
    if mijoz['kafil_bormi'] == 'ha':
        print(f"Kafil daromadi: {mijoz['kafil_daromadi']:,} som")
        print(f"Kafil kredit tarixi: {mijoz['kafil_kredit_tarixi'].upper()}")
    print(f"Ish joyi turi: {mijoz['ish_joyi_turi'].upper()}")
    print(f"Oylik majburiyat: {mijoz['oylik_majburiyat']:,} som")

    print("\n" + "="*60)
    print("KREDIT QARORI")
    print("="*60)

    try:
        features = {}
        for col in oz_features:
            if col.endswith('_encoded'):
                original_col = col.replace('_encoded', '')
                if original_col in label_encoders:
                    features[col] = label_encoders[original_col].transform([mijoz[original_col]])[0]
            else:
                features[col] = mijoz[col]

        X_mijoz = pd.DataFrame([features])
        natija = model.predict(X_mijoz)[0]
        ehtimollik = model.predict_proba(X_mijoz)[0][1] if natija == 1 else model.predict_proba(X_mijoz)[0][0]

        if natija == 1:
            print("KREDIT BERISH TAVSIYA ETILADI!")
            print(f"Ishonch darajasi: {ehtimollik * 100:.1f}%")
            maksimal_kredit = mijoz['daromad'] * 3
            print(f"Tavsiya etiladigan maksimal kredit: {maksimal_kredit:,.0f} som")
        else:
            print("KREDIT BERISH TAVSIYA ETILMAYDI!")
            print(f"Xavf darajasi: {ehtimollik * 100:.1f}%")
            print("\nRad etish sabablari:")
            if mijoz['kredit_tarixi'] == 'yomon':
                print("  Yomon kredit tarixi")
            if mijoz['kechiktirilgan_tolovlar'] > 5:
                print(f"  {mijoz['kechiktirilgan_tolovlar']} marta kechiktirilgan tolov")
            if mijoz['ish_joyi_turi'] == 'ishsiz':
                print("  Ish joyi yoq")
            if mijoz['jami_qarz'] > mijoz['daromad'] * 3:
                print("  Qarz miqdori daromaddan juda yuqori")
            if mijoz['kafil_bormi'] == 'yoq':
                print("  Kafil mavjud emas")
    except Exception as e:
        if mijoz['kredit_berilsinmi'] == 1:
            print("KREDIT BERISH MUMKIN")
        else:
            print("KREDIT BERISH MUMKIN EMAS")

    return baza, model, label_encoders, oz_features

def baza_korsat(baza):
    print("\n" + "="*70)
    print("BAZADAGI MIJOZLAR ROYXATI (50 TA)")
    print("="*70)
    print(f"{'No':<4} {'PASPORT':<14} {'ISMI':<22} {'DAROMAD':<12} {'KREDIT':<10}")
    print("-"*70)

    for idx, mijoz in baza.iterrows():
        kredit = "BERILADI" if mijoz['kredit_berilsinmi'] == 1 else "BERILMAYDI"
        print(f"{idx+1:<4} {mijoz['pasport']:<14} {mijoz['ism_familya']:<22} {mijoz['daromad']:<12,} {kredit:<10}")

    beriladiganlar = baza['kredit_berilsinmi'].sum()
    print("-"*70)
    print(f"Jami: {len(baza)} mijoz | Kredit beriladigan: {beriladiganlar} | Berilmaydigan: {len(baza)-beriladiganlar}")

def main():
    print("="*70)
    print("BANK KREDIT RISK TIZIMI (50 TA MIJOZ BAZASI BILAN)")
    print("="*70)

    global baza, model, label_encoders, oz_features

    if os.path.exists(BAZA_FILE) and os.path.exists(MODEL_FILE):
        print("\nMavjud bazani yuklash...")
        baza = pd.read_csv(BAZA_FILE)
        print(f"{len(baza)} ta mijoz yuklandi!")

        print("Model yuklanmoqda...")
        model = joblib.load(MODEL_FILE)
        label_encoders = joblib.load('label_encoders_50.pkl')
        oz_features = joblib.load('oz_features_50.pkl')
    else:
        print("\nYangi 50 ta mijozdan iborat baza yaratilmoqda...")
        baza = yarat_baza_50()
        baza.to_csv(BAZA_FILE, index=False)
        print("50 ta mijoz bazasi yaratildi va saqlandi!")

        print("Model orgatilmoqda...")
        model, label_encoders, oz_features = oqit_model(baza)
        print("Model orgatildi va saqlandi!")

    while True:
        print("\n" + "="*60)
        print("ASOSIY MENYU")
        print("="*60)
        print("1. Mijozni tekshirish (pasport boyicha)")
        print("2. Yangi mijoz qoshish")
        print("3. Barcha mijozlarni korish")
        print("4. Chiqish")

        tanlov = input("\nTanlang (1-4): ").strip()

        if tanlov == '1':
            baza, model, label_encoders, oz_features = mijozni_tekshirish(baza, model, label_encoders, oz_features)
        elif tanlov == '2':
            baza, model, label_encoders, oz_features = yangi_mijoz_qoshish(baza, model, label_encoders, oz_features)
        elif tanlov == '3':
            baza_korsat(baza)
        elif tanlov == '4':
            print("\nDasturdan chiqildi. Xizmatdan foydalanganingiz uchun rahmat!")
            break
        else:
            print("Xato: 1-4 orasida tanlang!")

if __name__ == "__main__":
    main()